"""
FAISS vs Qdrant Comparison page.

Loads evaluation/results/faiss_vs_qdrant.csv (generated by scripts/compare_stores.py)
and displays latency charts, overlap tables, and summary statistics.
"""

import pathlib

import pandas as pd
import streamlit as st

RESULTS_PATH = pathlib.Path(__file__).resolve().parent.parent.parent / "evaluation/results/faiss_vs_qdrant.csv"

st.title("FAISS vs Qdrant Comparison")


def render_comparison(df: pd.DataFrame) -> None:
    """Render charts and tables for the comparison DataFrame."""

    st.subheader("Latency Comparison (ms)")
    latency_df = df[["query", "faiss_latency_ms", "qdrant_latency_ms"]].copy()
    latency_df = latency_df.rename(
        columns={"faiss_latency_ms": "FAISS (ms)", "qdrant_latency_ms": "Qdrant (ms)"}
    )
    latency_df = latency_df.set_index("query")
    st.bar_chart(latency_df)

    st.subheader("Chunk Overlap per Query")
    overlap_df = df[["query", "faiss_chunks", "qdrant_chunks", "overlap_count"]].copy()
    overlap_df = overlap_df.rename(
        columns={
            "faiss_chunks": "FAISS chunks",
            "qdrant_chunks": "Qdrant chunks",
            "overlap_count": "Overlap",
        }
    )
    st.dataframe(overlap_df, use_container_width=True)

    st.subheader("Summary Statistics")
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric(
            "Avg FAISS Latency",
            f"{df['faiss_latency_ms'].mean():.1f} ms",
        )
    with col2:
        st.metric(
            "Avg Qdrant Latency",
            f"{df['qdrant_latency_ms'].mean():.1f} ms",
        )
    with col3:
        st.metric(
            "Avg Chunk Overlap",
            f"{df['overlap_count'].mean():.1f}",
        )

    with st.expander("Raw Data"):
        st.dataframe(df, use_container_width=True)


if RESULTS_PATH.exists():
    df = pd.read_csv(RESULTS_PATH)
    render_comparison(df)
else:
    st.info(
        "No comparison results found yet.\n\n"
        "Run the comparison script to generate data:\n\n"
        "```bash\n"
        "python -m scripts.compare_stores\n"
        "```\n\n"
        f"Results will be saved to `{RESULTS_PATH}`."
    )

# ---------------------------------------------------------------------------
# Phase 6: ColPali vs Standard Retrieval
# ---------------------------------------------------------------------------

st.divider()
st.header("Phase 6: ColPali vs Standard Retrieval")

st.markdown(
    """
    ### What is ColPali?

    **ColPali** (Column-wise PaLI) is a visual document retrieval approach that treats
    each PDF page as an *image* rather than extracted text.  The pipeline works as follows:

    1. **Render** — each page of the PDF is rasterised to a PNG image (150 dpi).
    2. **Describe** — Gemini's vision model generates a comprehensive natural-language
       description of the page, capturing text content, tables, charts, and key figures.
    3. **Embed** — the description is embedded using `text-embedding-004`, producing a
       dense vector for the entire page.
    4. **Index** — page vectors are stored in a dedicated Qdrant collection
       (`ifc_colpali`), separate from the standard chunked-text index.
    5. **Retrieve** — at query time, **MaxSim scoring** computes the cosine similarity
       between the query embedding and every page embedding, returning the top-k pages
       whose description best matches the query.

    ### How is this different from standard retrieval?

    | | Standard RAG | ColPali-style |
    |---|---|---|
    | **Input unit** | Text chunk (~512 tokens) | Whole PDF page (image) |
    | **Indexing** | Direct text embedding | Gemini image → description → embed |
    | **Retrieval** | ANN search in Qdrant | MaxSim cosine over page vectors |
    | **Strength** | High recall on textual content | Captures layout, tables, charts |
    | **Weakness** | Misses visual/layout cues | Slower to build (one LLM call per page) |

    ColPali is especially effective for **financial reports** where data is often
    presented in tables, charts, or diagrams that lose structure when extracted as
    raw text.
    """
)

try:
    from vectorstore.qdrant_store import colpali_collection_info, COLPALI_COLLECTION

    _info = colpali_collection_info()
    if _info is not None:
        st.success(
            f"Collection **`{COLPALI_COLLECTION}`** exists — "
            f"{_info['points_count']} page vectors indexed."
        )
    else:
        st.warning(
            f"Collection **`{COLPALI_COLLECTION}`** has not been built yet.\n\n"
            "To build it, run:\n\n"
            "```bash\n"
            "python - <<'EOF'\n"
            "from multimodal.colpali_embeddings import build_colpali_documents\n"
            "from embeddings.gemini_embeddings import GeminiEmbeddings\n"
            "from vectorstore.qdrant_store import build_colpali_qdrant\n\n"
            "PDF = 'resources/documents/ifc-annual-report-2024-financials.pdf'\n"
            "docs = build_colpali_documents(PDF)\n"
            "build_colpali_qdrant(docs, GeminiEmbeddings())\n"
            "print(f'Indexed {len(docs)} pages into ifc_colpali')\n"
            "EOF\n"
            "```"
        )
except Exception as _e:
    st.info(
        f"Could not connect to Qdrant to check the `ifc_colpali` collection "
        f"({_e}).  Make sure Qdrant is running (`docker compose up qdrant`) "
        "before visiting this page."
    )
